## Se importan las librerías a usar

In [36]:
import pandas as pd, numpy as np

## Se setean algunas constantes a usar

In [37]:
# caracteres diversos
VIN = "- " * 1 # viñeta
CHARF = "\n" * 1 # saltos de línea

# valores para cálculos
RANGON = [0,1] # rango de normalización 

## Se imprimen los datos de la matriz inicial y la matriz normalizada

In [42]:
# normalización de la matriz 2D
def normalizar_matriz_2d(matriz):
    norm = np.linalg.norm(matriz)
    matriz_n = matriz/norm  # matriz_normaliada
    return matriz_n

# suma de los valores de un array 1D dado
def sum_vals_array_1d(array):
    res = 0
    for val in array:
        res += val

    return res

# impresión de los resultados
def imprimir_datos(matriz):
    # matriz inicial
    print(VIN, "Matríz inicial: ", matriz, end=CHARF)
    
    # dimensión de la matríz
    print(VIN, "Dimensión de la matríz: ", matriz.ndim, end=CHARF)

    # tamaño de la matríz
    print(VIN, "Tamaño de la matríz: ", matriz.shape, end=CHARF)

    # suma de las columnas de la matríz
    print(VIN, "Suma de las columnas de la matríz: ", numpy.sum(matriz, axis= 0), end=CHARF)

    # suma de las filas de la matríz
    print(VIN, "Suma de las filas de la matríz: ", numpy.sum(matriz, axis= 0), end=CHARF)

    # matríz normalizada
    matriz_n = normalizar_matriz_2d(matrizA)
    print(VIN, "Matríz normalizada: ", matriz_n, end=CHARF)
    
    # suma de las filas de la matríz normalizada
    sum_filas_matriz_n = numpy.sum(matriz_n, axis= 1)
    print(VIN, "Suma de las filas de la matríz: ", sum_filas_matriz_n, end=CHARF)
    
    # suma de las columnas de la matríz normalizada
    suma_cols_matriz_n = numpy.sum(matriz_n, axis= 0)
    print(VIN, "Suma de las columnas de la matríz: ", suma_cols_matriz_n, end=CHARF)

    # total suma de las columnas de la matríz normalizada
    print(VIN, "Total suma de las columnas de la matríz: ", sum_vals_array_1d(suma_cols_matriz_n), end=CHARF)

    # total suma de las columnas de la matríz normalizada
    print(VIN, "Total suma de las columnas de la matríz: ", sum_vals_array_1d(suma_cols_matriz_n), end=CHARF)


## Se imprime el promedio de fila (pesos(Wi))

## Se imprime el promedio de filas

## Se imprime el auto valor

## Se imprime el valor máximo de lambda

## Se imprime el índice de consistencia

## Se imprime la relación de consistencia

## Se setea la martiz inicial

In [39]:
array_inicial = [
    [1, 1/7, 5, 1/9],
    [7, 1, 7, 1/7],
    [1/5, 1/7, 11, 1/7],
    [9, 7, 7, 1]
]

## Comienza la ejecución de todas las tareas

In [43]:
def realiza_calculos():
    # se setea la matriz inicial
    matriz = np.array(array_inicial, float)

    # se imprimen los datos de la matriz inicial y la matriz normalizada
    imprimir_datos(matriz)

realiza_calculos()

-  Matríz inicial:  [[ 1.          0.14285714  5.          0.11111111]
 [ 7.          1.          7.          0.14285714]
 [ 0.2         0.14285714 11.          0.14285714]
 [ 9.          7.          7.          1.        ]]
-  Dimensión de la matríz:  2
-  Tamaño de la matríz:  (4, 4)
-  Suma de las columnas de la matríz:  [17.2         8.28571429 30.          1.3968254 ]
-  Matríz normalizada:  [[0.04844254 0.00692036 0.24221271 0.0053825 ]
 [0.33909779 0.04844254 0.33909779 0.00692036]
 [0.00968851 0.00692036 0.53286795 0.00692036]
 [0.43598287 0.33909779 0.33909779 0.04844254]]
-  Suma de las filas de la matríz:  [0.30295812 0.73355848 0.55639719 1.16262099]
-  Suma de las columnas de la matríz:  [0.83321171 0.40138106 1.45327624 0.06766577]
