## Se importan las librerías a usar

In [ ]:
import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

## Se setean las funciones

In [ ]:
def triangular(x, a, b, c):
    return np.maximum(np.minimum((x - a) / (b - a), (c - x) / (c - b)), 0)

def trapezoidal(x, a, b, c, d):
    return np.maximum(np.minimum(np.minimum((x - a)/(b - a), 1), (d - x)/(d - c)), 0)

def lineal_asc(x, a, b):
    return np.clip((x - a) / (b - a), 0, 1)

def lineal_desc(x, a, b):
    return np.clip((b - x) / (b - a), 0, 1)

def plot_funciones(x, funciones, etiquetas, titulo):
    plt.figure(figsize=(8, 4))
    for f, etiqueta in zip(funciones, etiquetas):
        plt.plot(x, f, label=etiqueta)
    plt.title(titulo)
    plt.xlabel('Universo de discurso')
    plt.ylabel('Grado de pertenencia')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

## Se setean los Conjuntos Difusos para el Conjunto de Datos "Sequía"

In [ ]:
# Definimos el rango de valores y la función de pertenencia

x = np.linspace(0, 1.5, 1000)

bajo = lineal_desc(x, 0, 0.5)
medio = triangular(x, 0.3, 0.75, 1.2)
alto = lineal_asc(x, 0.8, 1.5)

# Graficamos las funciones de pertenencia
plot_funciones(x, [bajo, medio, alto], ['Bajo', 'Medio', 'Alto'], 'Funciones de pertenencia: Sequía')

## Se setean los Conjuntos Difusos para el Conjunto de Datos "Precipitación"

In [ ]:
# Definimos el rango de valores y la función de pertenencia

x = np.linspace(-100, 60, 1000)
precipitacion = lineal_asc(x, -85, 1)

# Graficamos
plt.figure(figsize=(8, 4))
plt.plot(x, precipitacion, label='Precipitación', color='blue', linewidth=2)
plt.scatter([-85, 1], [0, 1], color='red')  # Puntos clave
plt.title('Función de pertenencia: Precipitación')
plt.xlabel('Precipitación (mm)')
plt.ylabel('μ(x)')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

## se imprime el promedio de filas

## se imprime el auto valor

## se imprime el valor máximo de lambda

## se imprime el índice de consistencia

## se imprime la relación de consistencia

## se setea la martiz inicial

In [39]:
array_inicial = [
    [1, 1/7, 5, 1/9],
    [7, 1, 7, 1/7],
    [1/5, 1/7, 11, 1/7],
    [9, 7, 7, 1]
]

## comienza la ejecución de todas las tareas

In [43]:
def realiza_calculos():
    # se setea la matriz inicial
    matriz = np.array(array_inicial, float)

    # se imprimen los datos de la matriz inicial y la matriz normalizada
    imprimir_datos(matriz)

realiza_calculos()

-  Matríz inicial:  [[ 1.          0.14285714  5.          0.11111111]
 [ 7.          1.          7.          0.14285714]
 [ 0.2         0.14285714 11.          0.14285714]
 [ 9.          7.          7.          1.        ]]
-  Dimensión de la matríz:  2
-  Tamaño de la matríz:  (4, 4)
-  Suma de las columnas de la matríz:  [17.2         8.28571429 30.          1.3968254 ]
-  Matríz normalizada:  [[0.04844254 0.00692036 0.24221271 0.0053825 ]
 [0.33909779 0.04844254 0.33909779 0.00692036]
 [0.00968851 0.00692036 0.53286795 0.00692036]
 [0.43598287 0.33909779 0.33909779 0.04844254]]
-  Suma de las filas de la matríz:  [0.30295812 0.73355848 0.55639719 1.16262099]
-  Suma de las columnas de la matríz:  [0.83321171 0.40138106 1.45327624 0.06766577]
