# Script Análisis de Matrices

In [ ]:
A continuación se definen las diferentes funciones requeridas para realizar una evaluación multicriterio difusa o clásica, contando con:

- Matrices de juicio por pares.
- Evaluación de consistencia.
- Cálculo de pesos propios.
- Ajustes por linealización.

### Estructura general del script

Cada bloque del script sigue este patrón:

1.	MatrizInicial.- Contiene datos brutos de entrada.
2.	Análisis de matrices.- Aquí se calculan algunos parámetros útiles para el posterior análisis.
3.  Evaluación de la calidad de los datos de la matriz.- Se buscará validar la consistencia de los datos a fin de pasar a posteriores an´


## Se importan las librerías a usar

In [6]:
import pandas as pd, numpy as np

## Se setean algunas constantes a usar

In [7]:
# caracteres diversos
VIN = "- " * 1 # viñeta
CHARF = "\n" * 1 # saltos de línea

# valores para cálculos
RANGON = [0,1] # rango de normalización 

## Se imprimen los datos de la matriz inicial y las diferentes operaciones

In [8]:
# impresión de los resultados
def imprimir_datos(array_inicial, matriz):
    # matriz inicial
    print(VIN, "Matríz inicial: ", matriz, end=CHARF)
    
    # dimensión de la matríz
    print(VIN, "Dimensión de la matríz: ", matriz.shape, end=CHARF)

    # tamaño de la matríz
    print(VIN, "Tamaño de la matríz: ", matriz.size, end=CHARF)

    # suma de las columnas de la matríz
    suma_columnas = matriz.sum(axis= 0)
    print(VIN, "Suma de las columnas de la matríz: ", suma_columnas, end=CHARF)

    # suma de las filas de la matríz
    suma_filas = matriz.sum(axis= 1)
    print(VIN, "Suma de las filas de la matríz: ", suma_filas, end=CHARF)

    # matríz normalizada
    matriz_n = matriz / suma_columnas
    print(VIN, "Matríz normalizada: ", matriz_n, end=CHARF)
    
    # suma de las filas de la matríz normalizada
    sum_filas_matriz_n = matriz_n.sum(axis=1)
    print(VIN, "Suma de las filas de la matríz: ", sum_filas_matriz_n.round(4), end=CHARF)
    
    # suma de las columnas de la matríz normalizada
    suma_cols_matriz_n = matriz_n.sum(axis= 0)
    print(VIN, "Suma de las columnas de la matríz: ", suma_cols_matriz_n.round(4), end=CHARF)

    # pesos (Wi)
    fila_promedio = matriz.mean(axis=1) # promedio de fila
    pesos = fila_promedio / fila_promedio.sum() # pesos normalizados
    print(VIN, "Promedio filas: ", fila_promedio.round(4), end=CHARF)
    print(VIN, "Pesos (Wi): ", pesos.round(4), end=CHARF)
    
    # autovalor (lambda)
    producto_matriz = array_inicial @ pesos
    autovalores = producto_matriz / pesos
    print(VIN, "Autovalores: ", autovalores.round(4), end=CHARF)

    # lambda max
    lambda_max = autovalores.mean()
    print(VIN, "Lambda max: ", lambda_max.round(4), end=CHARF)

    # índice de consistencia (CI)
    n = matriz.shape[0]
    CI = (lambda_max - n) / (n - 1)
    print(VIN, "Índice de consistencia (CI): ", CI.round(4), end=CHARF)

    # relación de consistencia (CR)
    # Valores de RI para n = 1 hasta 10
    RI_dict = {1: 0.00, 2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
    RI = RI_dict[n]
    CR = CI / RI if RI != 0 else 0
    print(VIN, "Relación de consistencia (CR): ", CR.round(4), end=CHARF)
    


## Se setea la matriz inicial

In [9]:
array_inicial = [
    [1, 1/7, 5, 1/9],
    [7, 1, 7, 1/7],
    [1/5, 1/7, 11, 1/7],
    [9, 7, 7, 1]
]

## Comienza la ejecución de todas las tareas

In [10]:
def realiza_calculos():
    # se setea la matriz inicial
    matriz = np.array(array_inicial, float)

    # se imprimen los datos de la matriz inicial y la matriz normalizada
    imprimir_datos(array_inicial, matriz)

realiza_calculos()

-  Matríz inicial:  [[ 1.          0.14285714  5.          0.11111111]
 [ 7.          1.          7.          0.14285714]
 [ 0.2         0.14285714 11.          0.14285714]
 [ 9.          7.          7.          1.        ]]
-  Dimensión de la matríz:  (4, 4)
-  Tamaño de la matríz:  16
-  Suma de las columnas de la matríz:  [17.2         8.28571429 30.          1.3968254 ]
-  Suma de las filas de la matríz:  [ 6.25396825 15.14285714 11.48571429 24.        ]
-  Matríz normalizada:  [[0.05813953 0.01724138 0.16666667 0.07954545]
 [0.40697674 0.12068966 0.23333333 0.10227273]
 [0.01162791 0.01724138 0.36666667 0.10227273]
 [0.52325581 0.84482759 0.23333333 0.71590909]]
-  Suma de las filas de la matríz:  [0.3216 0.8633 0.4978 2.3173]
-  Suma de las columnas de la matríz:  [1. 1. 1. 1.]
-  Promedio filas:  [1.5635 3.7857 2.8714 6.    ]
-  Pesos (Wi):  [0.1099 0.2662 0.2019 0.4219]
-  Autovalores:  [10.955   9.4268 11.5958 11.1119]
-  Lambda max:  10.7724
-  Índice de consistencia (CI):  2